version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python main.py"

    ports:
      - 8009:5000 #port on local machine : port on docker container instance
    volumes:
      - .:/app
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python consumer.py"

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306 #port on local machine: port on docker container instance
